name: Greet on commit

on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Greet
        run: |
          echo "Hello! Thanks for committing to the main branch."